# This is the test docker-compose.yml override file for Github Actions -
# it is not intended to be used on it's own but instead layered into the
# normal test docker compose so it can be ran in CI.
version: "3.6"
services:
  webserver:
    user: 1001:121

